In [ ]:
import pandas as pd

In [ ]:
data = pd.read_csv('data/vehicles/vehicles_messy.csv')

/Users/germfy/anaconda3/envs/python38/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3062: DtypeWarning: Columns (70,71,72,73,74,76,79) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [ ]:
data.head(10)

,barrels08,barrelsA08,charge120,charge240,city08,city08U,cityA08,cityA08U,cityCD,cityE,...,mfrCode,c240Dscr,charge240b,c240bDscr,createdOn,modifiedOn,startStop,phevCity,phevHwy,phevComb
0,15.695714,0.0,0.0,0.0,19,0.0,0,0.0,0.0,0.0,...,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0
1,29.964545,0.0,0.0,0.0,9,0.0,0,0.0,0.0,0.0,...,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0
2,12.207778,0.0,0.0,0.0,23,0.0,0,0.0,0.0,0.0,...,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0
3,29.964545,0.0,0.0,0.0,10,0.0,0,0.0,0.0,0.0,...,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0
4,17.347895,0.0,0.0,0.0,17,0.0,0,0.0,0.0,0.0,...,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0
5,14.982273,0.0,0.0,0.0,21,0.0,0,0.0,0.0,0.0,...,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0
6,13.184400,0.0,0.0,0.0,22,0.0,0,0.0,0.0,0.0,...,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0
7,13.733750,0.0,0.0,0.0,23,0.0,0,0.0,0.0,0.0,...,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0
8,12.677308,0.0,0.0,0.0,23,0.0,0,0.0,0.0,0.0,...,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0
9,13.184400,0.0,0.0,0.0,23,0.0,0,0.0,0.0,0.0,...,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0

In [ ]:
data.shape

(37843, 83)

In [ ]:
data.isnull()

,barrels08,barrelsA08,charge120,charge240,city08,city08U,cityA08,cityA08U,cityCD,cityE,...,mfrCode,c240Dscr,charge240b,c240bDscr,createdOn,modifiedOn,startStop,phevCity,phevHwy,phevComb
0,False,False,False,False,False,False,False,False,False,False,...,True,True,False,True,False,False,True,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,True,True,False,True,False,False,True,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,True,True,False,True,False,False,True,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,True,True,False,True,False,False,True,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,True,True,False,True,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37838,False,False,False,False,False,False,False,False,False,False,...,True,True,False,True,False,False,True,False,False,False
37839,False,False,False,False,False,False,False,False,False,False,...,True,True,False,True,False,False,True,False,False,False
37840,False,False,False,False,False,False,False,False,False,False,...,True,True,False,True,False,False,True,False,False,False
37841,False,False,False,False,False,False,False,False,False,False,...,True,True,False,True,False,False,True,False,False,False
37842,False,False,False,False,False,False,False,False,False,False,...,True,True,False,True,False,False,True,False,False,False

In [ ]:
data.isnull().sum()

barrels08         0
barrelsA08        0
charge120         0
charge240         0
city08            0
              ...
modifiedOn        0
startStop     31705
phevCity          0
phevHwy           0
phevComb          0
Length: 83, dtype: int64

In [ ]:
columnas_nulas = data.isnull().sum()
columnas_nulas[columnas_nulas > 0]

cylinders       123
displ           120
drive          1189
eng_dscr      15403
trany            11
guzzler       35562
trans_dscr    22796
tCharger      32657
sCharger      37177
atvType       34771
fuelType2     36435
rangeA        36440
evMotor       37281
mfrCode       30818
c240Dscr      37806
c240bDscr     37807
startStop     31705
dtype: int64

In [ ]:
#columnas_nulas[columnas_nulas > 10000].index
print(data.shape)
columnas_a_eliminar = list(columnas_nulas[columnas_nulas > 10000].index)
data = data.drop(columnas_a_eliminar, axis = 1)
print(data.shape)

(37843, 83)
(37843, 70)

In [ ]:
displ_nulos = data[(data['displ'].isnull()==True)]
displ_nulos = displ_nulos[['year', 'make', 'model', 'trany', 'drive','fuelType','cylinders', 'displ']]

In [ ]:
data[['displ', 'cylinders']] = data[['displ', 'cylinders']].fillna(0)

In [ ]:
test = data[(data['cylinders']==0) & (data['fuelType']=='Regular')]
test[['year', 'make', 'model', 'trany', 'drive','fuelType','cylinders', 'displ']]

,year,make,model,trany,drive,fuelType,cylinders,displ
21413,1985,Subaru,RX Turbo,Manual 5-spd,4-Wheel Drive,Regular,0.0,0.0
21414,1985,Subaru,RX Turbo,Manual 5-spd,4-Wheel Drive,Regular,0.0,0.0
21506,1986,Mazda,RX-7,Manual 5-spd,Rear-Wheel Drive,Regular,0.0,1.3

In [ ]:
data.loc[(data['cylinders']==0) & (data['fuelType']=='Regular') & (data['make']=='Subaru'), 'cylinders'] = 4
data.loc[(data['cylinders']==4) & (data['displ']==0) & (data['make']=='Subaru'), 'displ'] = 1.7

In [ ]:
test = data[(data['displ']==1.7) & (data['fuelType']=='Regular') & (data['make']=='Subaru')]
test[['year', 'make', 'model', 'trany', 'drive','fuelType','cylinders', 'displ']]

,year,make,model,trany,drive,fuelType,cylinders,displ
21413,1985,Subaru,RX Turbo,Manual 5-spd,4-Wheel Drive,Regular,4.0,1.7
21414,1985,Subaru,RX Turbo,Manual 5-spd,4-Wheel Drive,Regular,4.0,1.7

In [ ]:
data[(data['cylinders']==4) & (data['displ']==0) & (data['make']=='Subaru')]

Empty DataFrame
Columns: [barrels08, barrelsA08, charge120, charge240, city08, city08U, cityA08, cityA08U, cityCD, cityE, cityUF, co2, co2A, co2TailpipeAGpm, co2TailpipeGpm, comb08, comb08U, combA08, combA08U, combE, combinedCD, combinedUF, cylinders, displ, drive, engId, feScore, fuelCost08, fuelCostA08, fuelType, fuelType1, ghgScore, ghgScoreA, highway08, highway08U, highwayA08, highwayA08U, highwayCD, highwayE, highwayUF, hlv, hpv, id, lv2, lv4, make, model, mpgData, phevBlended, pv2, pv4, range, rangeCity, rangeCityA, rangeHwy, rangeHwyA, trany, UCity, UCityA, UHighway, UHighwayA, VClass, year, youSaveSpend, charge240b, createdOn, modifiedOn, phevCity, phevHwy, phevComb]
Index: []

[0 rows x 70 columns]

In [ ]:
import numpy as np
varianza_baja = []

for columna in data._get_numeric_data():
    minimo = min(data[columna])
    percentil_90 = np.percentile(data[columna], 90)
    if percentil_90 == minimo:
        varianza_baja.append(columna)

varianza_baja

['barrelsA08',
 'charge120',
 'charge240',
 'cityA08',
 'cityA08U',
 'cityCD',
 'cityE',
 'cityUF',
 'co2A',
 'co2TailpipeAGpm',
 'combA08',
 'combA08U',
 'combE',
 'combinedCD',
 'combinedUF',
 'fuelCostA08',
 'ghgScoreA',
 'highwayA08',
 'highwayA08U',
 'highwayCD',
 'highwayE',
 'highwayUF',
 'phevBlended',
 'range',
 'rangeCity',
 'rangeCityA',
 'rangeHwy',
 'rangeHwyA',
 'UCityA',
 'UHighwayA',
 'charge240b',
 'phevCity',
 'phevHwy',
 'phevComb']

In [ ]:
data = data.drop(varianza_baja, axis = 1)

In [ ]:
estadisticos = data.describe().transpose()
estadisticos['outlier'] = estadisticos['75%'] - estadisticos['25%']

In [ ]:
data.dtypes

barrels08         float64
city08              int64
city08U           float64
co2                 int64
co2TailpipeGpm    float64
comb08              int64
comb08U           float64
cylinders         float64
displ             float64
drive              object
engId               int64
feScore             int64
fuelCost08          int64
fuelType           object
fuelType1          object
ghgScore            int64
highway08           int64
highway08U        float64
hlv                 int64
hpv                 int64
id                  int64
lv2                 int64
lv4                 int64
make               object
model              object
mpgData            object
pv2                 int64
pv4                 int64
trany              object
UCity             float64
UHighway          float64
VClass             object
year                int64
youSaveSpend        int64
createdOn          object
modifiedOn         object
dtype: object

In [ ]:
data['year'] = data['year'].astype('object')

In [ ]:
data.dtypes

barrels08         float64
city08              int64
city08U           float64
co2                 int64
co2TailpipeGpm    float64
comb08              int64
comb08U           float64
cylinders         float64
displ             float64
drive              object
engId               int64
feScore             int64
fuelCost08          int64
fuelType           object
fuelType1          object
ghgScore            int64
highway08           int64
highway08U        float64
hlv                 int64
hpv                 int64
id                  int64
lv2                 int64
lv4                 int64
make               object
model              object
mpgData            object
pv2                 int64
pv4                 int64
trany              object
UCity             float64
UHighway          float64
VClass             object
year               object
youSaveSpend        int64
createdOn          object
modifiedOn         object
dtype: object

In [ ]:
set(data['trany'])

{'Auto (AV)',
 'Auto (AV-S6)',
 'Auto (AV-S8)',
 'Auto(A1)',
 'Auto(AM-S6)',
 'Auto(AM-S7)',
 'Auto(AM-S8)',
 'Auto(AM-S9)',
 'Auto(AM5)',
 'Auto(AM6)',
 'Auto(AM7)',
 'Auto(AM8)',
 'Auto(AV-S6)',
 'Auto(AV-S7)',
 'Auto(AV-S8)',
 'Auto(L3)',
 'Auto(L4)',
 'Automatic (A1)',
 'Automatic (A6)',
 'Automatic (AM5)',
 'Automatic (AM6)',
 'Automatic (AV)',
 'Automatic (AV-S6)',
 'Automatic (S4)',
 'Automatic (S5)',
 'Automatic (S6)',
 'Automatic (S7)',
 'Automatic (S8)',
 'Automatic (S9)',
 'Automatic (variable gear ratios)',
 'Automatic 3-spd',
 'Automatic 4-spd',
 'Automatic 5-spd',
 'Automatic 6-spd',
 'Automatic 6spd',
 'Automatic 7-spd',
 'Automatic 8-spd',
 'Automatic 9-spd',
 'Manual 3-spd',
 'Manual 4-spd',
 'Manual 4-spd Doubled',
 'Manual 5 spd',
 'Manual 5-spd',
 'Manual 6-spd',
 'Manual 7-spd',
 'Manual(M7)',
 nan}

In [ ]:
data['trany'] = data['trany'].str.replace('-', '')

In [ ]:
data.trany.unique()

array(['Manual 5spd', 'Automatic 3spd', 'Automatic 4spd',
       'Automatic 5spd', 'Manual 4spd', 'Manual 3spd', 'Manual 6spd',
       'Automatic (S5)', 'Automatic (variable gear ratios)',
       'Automatic 6spd', 'Automatic (S6)', nan, 'Automatic (S4)',
       'Automatic 7spd', 'Automatic (S7)', 'Automatic (S8)',
       'Automatic (AM5)', 'Auto(AM6)', 'Auto(AVS7)', 'Automatic (A6)',
       'Automatic (AVS6)', 'Auto(AM7)', 'Manual 4spd Doubled',
       'Manual 5 spd', 'Automatic (AM6)', 'Manual 7spd', 'Auto(L4)',
       'Auto(L3)', 'Automatic (AV)', 'Auto (AVS6)', 'Auto(AM5)',
       'Auto(AVS6)', 'Auto (AVS8)', 'Automatic 8spd', 'Auto(AVS8)',
       'Automatic (A1)', 'Auto (AV)', 'Auto(AMS6)', 'Auto(AMS7)',
       'Automatic 9spd', 'Automatic (S9)', 'Auto(AMS8)', 'Auto(A1)',
       'Auto(AM8)', 'Manual(M7)', 'Auto(AMS9)'], dtype=object)

In [ ]:
data['trany'] = data['trany'].str.replace('Automatic', 'Auta')

In [ ]:
antes = len(data)
data = data.drop_duplicates()
despues = len(data)
print(f'Numero de registros eliminados:{antes-despues}')

Numero de registros eliminados:0

In [ ]:
select_columns = ['make', 'model', 'year', 'displ', 'cylinders',
                  'trany', 'drive', 'VClass','fuelType','barrels08',
                  'city08', 'highway08', 'comb08', 'co2TailpipeGpm', 'fuelCost08']

antes = len(data)
data = data[select_columns].drop_duplicates()
despues = len(data)
print(f'Numero de registros eliminados:{antes-despues}')

Numero de registros eliminados:0

In [ ]:
antes = len(data)
data.drop_duplicates(subset=select_columns, inplace=True)
#data = data.iloc[data['year'].drop_duplicates().unique()]
despues = len(data)
print(f'Numero de registros eliminados:{antes-despues}')

Numero de registros eliminados:885

In [ ]:
data.columns